version: '3.8'
services:
   db:
      image: postgres
      restart: always
      environment:
         POSTGRES_USER: flowable
         POSTGRES_PASSWORD: flowable
         POSTGRES_DB: flowable
      ports:
         - 5432:5432
      volumes:
         - ./data:/var/lib/postgresql/data
